// images.js

export const rec1 = require('./mocks/Rectangle-1.png');
export const rec2 = require('./mocks/Rectangle-2.png');
export const rec3 = require('./mocks/Rectangle.png');
export const userflow = require('./Userflow.png');
export const persona1 = require('./persona2/Frame 209.png');
export const persona2 = require('./persona2/Frame 211.png');
export const persona3 = require('./persona2/Frame 212.png');
export const empathy1 = require('./empathy1.png');
export const empathy2 = require('./empathy2.png');
export const mock3 = require('./mock3.png');
export const lofi1 = require('./lofi/Login_wireframelofi.png');
export const lofi2 = require('./lofi/Homescreen_wireframelofi.png');
export const lofi3 = require('./lofi/Order_summary_wireframelofi.png');
export const lofi4 = require('./lofi/PRODUCT_wireframelofi.png');
export const lofi5 = require('./lofi/Vegg-listlofi.png');
export const lofi6 = require('./lofi/13 Pro - 65lofi-1.png');
export const lofi7 = require('./lofi/13 Pro - 65lofi.png');
export const lofi8 = require('./lofi/Checkoutlofi.png');
export const process = require('./Group667.png');
export const mock = require('./Frame836.png');
export const sol = require('./illustration/solution.png');
export const goal = require('./illustration/goal.png');
export const overview = require('./illustration/overview.png');
export const prob = require('./illustration/problem.png');
export const  screen = require('./screens (1).png');

export const  scr1 = require('./hi-fi/iPhone 13/on1.png');
export const  scr2 = require('./hi-fi/iPhone 13/on2.png');
export const  scr3 = require('./hi-fi/iPhone 13/on3.png');
export const  scr4 = require('./hi-fi/iPhone 13/on4.png');
export const  scr5 = require('./hi-fi/iPhone 13/on5.png');
export const  scr6 = require('./hi-fi/iPhone 13/on6.png');
export const  scr7 = require('./hi-fi/others/13 Pro - 14.png');
export const  scr8 = require('./hi-fi/others/13 Pro - 15.png');
export const  scr9 = require('./hi-fi/others/13 Pro - 17.png');
export const  scr10 = require('./hi-fi/others/13 Pro - 18.png');
export const  scr11= require('./hi-fi/others/13 Pro - 19.png');
export const  scr12 = require('./hi-fi/others/13 Pro - 22.png');
export const  scr13= require('./hi-fi/others/13 Pro - 63.png');
export const  scr14= require('./hi-fi/others/13 Pro - 64.png')
// export const  scr15 = require('./hi-fi/13 Pro - 5.png');
// export const  scr15 = require('./hi-fi/Login.png');
// export const  scr16 = require('./hi-fi/Sign up.png');
